on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X https://hub.docker.com/api/build/v1/source/5d8ca6fb-d382-4b97-9d86-2212e0d09227/trigger/c40b8701-3e44-4b2a-98e3-d565fdcedc85/call/
